INHERIT: !ENV MKDOCS_NUMTIDE_THEME

### Site metadata ###

site_name: treefmt
site_description: one CLI to format your repo
site_url: https://numtide.github.io/treefmt/
repo_name: 'numtide/treefmt'
repo_url: https://github.com/numtide/treefmt
edit_uri: edit/main/docs

### Navigation ###

nav:
  - Home: index.md
  - QuickStart:
      - About: quickstart.md
      - Installation: installation.md
      - Configuration: treefmt-configuration.md
  - Usage: usage.md
  - Integrations: integrations.md
  - Formatters: 
      - About: index-formatters.md
      - Formatter Specification: formatters-spec.md
      - Known Formatters: formatters.md
  - FAQ: faq.md
  - Contributing: contributing.md
