# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatters.black]
command = "black"
includes = ["*.py"]

[formatters.elm]
command = "elm-format"
options = ["--yes"]
includes = ["*.elm"]

[formatters.gofmt]
includes = ["*.go"]
command = "gofmt"
options = ["-w"]

[formatters.ormolu]
command = "ormolu"
options = [
    "--ghc-opt", "-XBangPatterns",
    "--ghc-opt", "-XPatternSynonyms",
    "--ghc-opt", "-XTypeApplications",
    "--mode", "inplace",
    "--check-idempotence",
]
includes = ["*.hs"]
excludes = ["haskell/"]

[formatters.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.js"]

[formatters.rustfmt]
command = "rustfmt"
options = ["--edition", "2018"]
includes = ["rust/**/*.rs"]
excludes = []

[formatters.shfmt]
command = "shfmt"
options = [
    "-i",
    "2",  # indent 2
    "-s",  # simplify the code
    "-w",  # write back to the file
]
includes = ["*.sh"]
excludes = []
