# fmt is the universal code formatter - https://github.com/numtide/fmt

[formatters.black]
files = [ "*.py" ]
command = "black"
options = [ ]

[formatters.cargo]
files = [ "*.rs" ]
includes = [ "rust/" ]
excludes = []
command = "cargo"
options = [ "fmt", "--" ]

[formatters.gofmt]
files = [ "*.go" ]
command = "gofmt"
options = [ "-w" ]

[formatters.ormolu]
files = "*.hs" # / "*.hs" / "Makefile" mandatory
excludes = [ "haskell/" ] # blacklisted folder/files.
command = "ormolu"
options = [
  "--ghc-opt", "-XBangPatterns",
  "--ghc-opt", "-XPatternSynonyms",
  "--ghc-opt", "-XTypeApplications",
  "--mode", "inplace",
  "--check-idempotence"
]

[formatters.prettier]
files = [ "*.js" ]
command = "prettier"
options = [ "--write" ]
