# fmt is the universal code formatter - https://github.com/numtide/fmt
[formatters.ormolu]
files = "*.hs" # / "*.hs" / "Makefile" mandatory
excludes = [ "haskell/" ] # blacklisted folder/files.
command = "ormolu"
options = [
  "--ghc-opt", "-XBangPatterns",
  "--ghc-opt", "-XPatternSynonyms",
  "--ghc-opt", "-XTypeApplications",
  "--mode", "inplace",
  "--check-idempotence"
]

[formatters.cargo]
files = [ "*.rs" ]
includes = [ "rust/" ]
excludes = []
command = "cargo"
options = [ "fmt", "--" ]
